version: "3.9"

services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: verdaccio_root_path
    ports:
      - 4873:4873
    volumes:
      - verdaccio:/verdaccio

  # nginx:
  #   image: nginx:alpine
  #   restart: always
  #   ports:
  #     - 80:80
  #   volumes:
  #     - /www/public
  #   volumes_from:
  #     - verdaccio
  #   links:
  #     - verdaccio:verdaccio

volumes:
  verdaccio:
    driver: local
